markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine:
  syntax_highlighter: rouge
permalink: /posts/:categories/:title

baseurl: ""
theme: jekyll-theme-cayman

url: http://jiangfan233.github.io/
author: jiang

head:
- tag: meta
  var:
  - key: name
    value: viewport
  - key: content
    value: width=device-width, initial-scale=1.0, maximum-scale=1
- tag: link # 网站大图标
  var:
  - key: rel
    value: apple-touch-icon-precomposed
  - key: href
    value: ./public/image/avatar.jpg
- tag: link # 小图标，同上
  var:
  - key: rel
    value: 'shortcut icon'
  - key: href
    value: ./public/image/avatar.jpg

body:
  theme-base: theme-base-0d # 可选的值08~0f
  layout-reverse: true # 开启后sidebar在右边，反之左边
  sidebar-overlay: true # 开启后正文不随sidebar移动而移动

sidebar:
  avatar: # 侧边栏显示的头像
    enable: true
    img: ./public/image/LAvatar.jpg # 头像的地址
  description: '<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=100% height=52 src="//music.163.com/outchain/player?type=2&id=1311263606&auto=0&height=32"></iframe>'
  social:
  - title: jiangdadadada@outlook.com # email
    href: mailto:jiangdadadada@outlook.com.com
    class: 'fas fa-envelope fa-fw'
  - title: github
    href: //github.com/jiangfan233
    class: 'fab fa-github fa-fw'
  - title: 794110493 # qq
    class: 'fab fa-qq fa-fw'
  nav:
  - title: '<i class="fas fa-home fa-fw"></i> 首页'
    href: /
  - title: '<i class="fas fa-tags fa-fw"></i> 标签'
    href: /tags
  - title: '<i class="fas fa-archive fa-fw"></i> 归档'
    href: /archive
  simple_jekyll_search:
    enable: true
    autoloader: /public/simple-jekyll-search/autoloader.js
    stylesheet: //cdn.jsdelivr.net/gh/wu-kan/wu-kan.github.io@1788f1b6c2e12cca626b85f25749f99ca0c7aad0/public/simple-jekyll-search/search_box.min.css
    src: //cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js
    placeholder: 搜索博文
    json: /public/simple-jekyll-search/search.json

index:
  showtag:
  - 网络
  - golang
  - infrastructure

post:
  meta:
    enable: true
    date: true    